spring:
  application:
    name: aggregator  # ✅ Имя для Eureka

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true

  cloud:
    config:
      enabled: false
    import-check:
      enabled: false

logging:
  level:
    root: INFO

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka