server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewm-db
    username: stat
    password: stat

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none