server:
  port: 0

spring:
  application:
    name: main-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-db}
    username: ${SPRING_DATASOURCE_USERNAME:stat}
    password: ${SPRING_DATASOURCE_PASSWORD:stat}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/