server:
  port: 0

spring:
  application:
    name: main-service

  datasource:
    url: jdbc:postgresql://localhost:6542/ewm-db
    username: stat
    password: stat

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
