server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-db
    username: stat
    password: stat

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none

statsServiceId: stats-server