server:
  port: 0

spring:
  application:
    name: stats-server

  datasource:
    url: jdbc:postgresql://localhost:6541/stats-db
    username: stat
    password: stat

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
