server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # === USER-SERVICE ===
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # === COMMENT-SERVICE ===
        ## Admin
        - id: comment-service-admin
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**
        ## Public
        - id: comment-service-public
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments/**
        ## Private
        - id: comment-service-private
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**

        # === EVENT-SERVICE ===

        # INTERNAL
        - id: event-service-internal
          uri: lb://event-service
          predicates:
            - Path=/internal/events/**

        ## Admin
        - id: event-service-admin-events
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
        - id: event-service-admin-categories
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**
        - id: event-service-admin-compilations
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        ## Public
        - id: event-service-public-categories
          uri: lb://event-service
          predicates:
            - Path=/categories/**
        - id: event-service-public-events
          uri: lb://event-service
          predicates:
            - Path=/events/**
        - id: event-service-public-compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        ## Private
        - id: event-service-private-events
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**

        # === REQUEST-SERVICE ===
        ## Private
        - id: request-service-private
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        ## Internal
        - id: request-service-internal
          uri: lb://request-service
          predicates:
            - Path=/internal/**

        # === STATS-SERVER ===
        - id: stats-server-hit
          uri: lb://stats-server
          predicates:
            - Path=/hit
        - id: stats-server-stats
          uri: lb://stats-server
          predicates:
            - Path=/stats

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true