server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # === USER-SERVICE ===
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # === EVENT-SERVICE ===
        - id: event-service-admin-events
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: event-service-categories
          uri: lb://event-service
          predicates:
            - Path=/categories/**

        - id: event-service-events
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: event-service-compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        # === REQUEST-SERVICE ===
        - id: request-service-private
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        # === COMMENT-SERVICE ===
        - id: comment-service-private
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**

        - id: comment-service-public
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments/**

        - id: comment-service-admin
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        # === STATS-SERVICE ===
        - id: stats-server-hit
          uri: lb://stats-server
          predicates:
            - Path=/hit

        - id: stats-server-stats
          uri: lb://stats-server
          predicates:
            - Path=/stats

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true